name: Nginx Docker CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t my-nginx-demo .

      - name: Run Container
      - run: docker run -d -p 8080:80 --name website my-nginx-demo .

logs:
  steps:
    uses: actions/checkout@v4
    name:listing container 
    run: docker ps -a

    name: Check logs
    run: docker logs website
  
deploy:
  needs: build
  runs-on: ubuntu-latest

  steps:
    - name: curl
      run: curl http://localhost:8080
