name: Nginx Docker CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t my-nginx-demo
      - run: docker run -d -p 8080:80 --name website my-nginx-demo
      - run: docker logs website
      - run: curl localhost:8080
